apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fishbowl-data
  namespace: default
  labels:
    app: fishbowl
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
